#!/bin/bash

PACKAGE_NAME="mysql"
PACKAGE_VERSION="8.0.34"
PACKAGE_ARCH="amd64"
PACKAGE_FILENAME="${PACKAGE_NAME}-${PACKAGE_VERSION}-${PACKAGE_ARCH}.deb"
DESCRIPTION="MySQL Database Server"

PACKAGE_DIR="$PACKAGE_NAME-$PACKAGE_VERSION-$PACKAGE_ARCH"
DEBIAN_DIR="$PACKAGE_DIR/DEBIAN"
INSTALL_DIR="$PACKAGE_DIR/usr/bin"

mkdir -p "$DEBIAN_DIR"
chmod 0755 "$DEBIAN_DIR"

mkdir -p "$INSTALL_DIR"
cp mysql "$INSTALL_DIR"

cat > "$DEBIAN_DIR/control" <<EOF
Package: $PACKAGE_NAME
Version: $PACKAGE_VERSION
Architecture: $PACKAGE_ARCH
Description: $DESCRIPTION
EOF

dpkg-deb --build "$PACKAGE_DIR" "$PACKAGE_FILENAME.deb"
rm -rf "$PACKAGE_DIR"
  
echo "Package $PACKAGE_FILENAME.deb created successfully."
