name: Build GOST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3.6.0

    - name: Install UPX
      run: sudo apt-get update && sudo apt-get install -y upx-ucl

    - name: Download and Install Go
      run: |
        GO_VERSION="1.20.7"
        wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin

    - name: Get latest release
      run: |
        latest_release_info=$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest)
        latest_version=$(echo "$latest_release_info" | grep '"tag_name":' | cut -d '"' -f 4)
        download_url="https://github.com/cloudflare/cloudflared/archive/$latest_version.zip"
        curl -LO "$download_url"
        unzip "$latest_version.zip"
        cd "cloudflared-$latest_version"
        go build -o cloudflared -trimpath -ldflags "-s -w -buildid=" ./cmd/cloudflared
        upx -o gost cloudflared
        sudo chmod a+x gost

    - name: Publish gost release
      id: publish
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          gost
        token: ${{ secrets.GITHUB_TOKEN }}
