name: Update Gost

on:
#  schedule:
#    - cron: '0 20 * * 0'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    name: Run Script

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Run Script
#        env:
#          GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
        run: |
          sudo chmod +x UpdateGost.sh
          sudo bash UpdateGost.sh
