name: Update Gost

on:
  schedule:
    - cron: '0 20 * * 0'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    name: Run Script
    env:
      GITHUB_TOKEN: ${{ GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Run Script
        run: |
          sudo chmod +x UpdateGost.sh
          sudo bash UpdateGost.sh
