name: Update Gost

on:
  schedule:
    - cron: '0 20 * * 0'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-20.04
    name: Run
    env:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Run Script
        run: |
          sudo chmod +x UpdateGost.sh
          sudo bash UpdateGost.sh

      - name: Check for cloudflared-arm
        run: |
          if [ -e cloudflared-arm ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add gost README.md
            git commit -m "Update Gost on $(date "+%Y/%m/%d %H:%M:%S")"
            git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{github.repository}}.git
            git push
          else
            echo "cloudflared-arm file does not exist, won't perform commit operation."
          fi

